# Generated by Django 4.2.7 on 2025-12-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eldlog_fuel_consumed_eldlog_total_engine_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fuel_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel used in gallons during trip', max_digits=10, null=True),
        ),
    ]
