# Generated by Django 4.2.7 on 2025-12-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trip_fuel_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fuel_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Fuel used in gallons during trip', max_digits=10, null=True),
        ),
    ]
