# Generated by Django 4.2.7 on 2025-12-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trip_fuel_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_engine_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_miles',
            field=models.FloatField(default=0.0),
        ),
    ]
