# Generated by Django 4.2.7 on 2026-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trip_total_engine_hours_trip_total_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('MANAGER', 'Manager')], default='DRIVER', max_length=10),
        ),
    ]
