# Generated by Django 4.2.7 on 2026-01-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vehicle_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Trip end time', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_odometer',
            field=models.FloatField(blank=True, help_text='Final odometer reading at trip end', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_efficiency',
            field=models.FloatField(blank=True, help_text='Miles per gallon', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='initial_odometer',
            field=models.FloatField(default=0.0, help_text='Initial odometer reading at trip start'),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_service_date',
            field=models.DateField(blank=True, help_text='Last vehicle service date', null=True),
        ),
    ]
