# Generated by Django 4.2.7 on 2026-01-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_trip_completion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
